#!/system/bootstrap/binary/busybox ash
BB_STATIC="/system/bootstrap/binary/busybox"
BOOT_CONF="/cache/recovery/bootmode.conf"
BP_PANIC="/cache/bp_panic"

#Check for stock kernel
if  [ -e /init_prep_keypad.sh ];
then

#Fix permissions
$BB_STATIC chmod 755 /system/bootstrap/script/*
$BB_STATIC chmod 755 /system/bootstrap/binary/*

#Insmod ext4 modules 
$BB_STATIC insmod /system/bootstrap/modules/jbd2.ko
$BB_STATIC insmod /system/bootstrap/modules/ext4.ko

# Mount cache to get bootmode
$BB_STATIC mount -o remount,rw /
$BB_STATIC mkdir /cache
$BB_STATIC mount -t auto -o nosuid,nodev,noatime,nodiratime,barrier=1 /dev/block/mmcblk1p24 /cache

# Set cpu to 1ghz
echo 1000000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# Check if device rebooted due BP-panic
if [ -e $BP_PANIC ]; then
$BB_STATIC rm $BP_PANIC
$BB_STATIC ash /system/bootstrap/script/2nd-boot.sh boot
fi

# Check if device rebooted in recovery mode
if [ -e $BOOT_CONF ]; then
if [ $($BB_STATIC cat $BOOT_CONF) == 'recovery' ]; then
$BB_STATIC rm $BOOT_CONF
$BB_STATIC ash /system/bootstrap/script/2nd-boot.sh recovery
fi
fi

# Disable button backlight
echo 0 > /sys/class/leds/button-backlight/brightness

BOOT_MODE="$(/system/bootstrap/binary/safestrapmenu > /dev/null 2>&1;echo $?)"

if [ $BOOT_MODE -eq 0 ]; then 
echo 0 > /sys/class/leds/button-backlight/brightness
$BB_STATIC ash /system/bootstrap/script/2nd-boot.sh recovery
elif [ $BOOT_MODE -eq 1 ]; then 
echo 0 > /sys/class/leds/button-backlight/brightness
$BB_STATIC ash /system/bootstrap/script/2nd-boot.sh boot
elif [ $BOOT_MODE -eq 2 ]; then 
echo 0 > /sys/class/leds/lcd-backlight/brightness
echo 0 > /sys/class/leds/button-backlight/brightness
# busybox sym link..
for cmd in $($BB_STATIC --list); do
    $BB_STATIC ln -s $BB_STATIC /sbin/$cmd
done
$BB_STATIC mount -o remount,rw /system
echo charge_adb > /dev/usb_device_mode
PATH=/sbin /system/bootstrap/binary/adbd &
rm /init_prep_keypad.sh
exit
elif [ $BOOT_MODE -eq 3 ]; then 
echo 0 > /sys/class/leds/button-backlight/brightness
$BB_STATIC ash /system/bootstrap/script/2nd-boot.sh uart
fi

fi
/system/bin/logwrapper.bin "$@"
