#!/system/bin/sh

BASEBAND_SWITCH_PROP="/data/property/persist.sys.new_baseband"
BASEBAND_BASE="/system/etc/motorola"

if [ -e $BASEBAND_SWITCH_PROP ]; then
    NEW_BASEBAND=`cat $BASEBAND_SWITCH_PROP`
    rm -f $BASEBAND_SWITCH_PROP

    if [ -d $BASEBAND_BASE/$NEW_BASEBAND ]; then
        busybox mount -o remount,rw /system
        rm -f $BASEBAND_BASE/bp_nvm_default/*
        cp -a $BASEBAND_BASE/$NEW_BASEBAND/* $BASEBAND_BASE/bp_nvm_default
        busybox mount -o remount,ro /system
    fi
fi

