#!/system/bin/sh
#
# load ip6table base kernel module (netfilter still buggy)

DEFYPLUS_KERNEL=0
if [ -f /proc/socinfo ]; then
    DEFYPLUS_KERNEL=1
fi

if [ "$DEFYPLUS_KERNEL" = "1" ]; then
    /system/xbin/insmod /system/lib/modules/ip6_tables.ko
fi

