#!/system/xbin/ash
#
# load green lens camera modules

export PATH="/system/xbin:$PATH"

log path is $PATH

DEFYPLUS_KERNEL=0
if [ -f /proc/socinfo ]; then
    DEFYPLUS_KERNEL=1
fi

CAMERA_DETECTED=0
if [ -c /dev/camera0 ]; then
    CAMERA_DETECTED=1
fi

if [ "$DEFYPLUS_KERNEL $CAMERA_DETECTED" = "1 0" ]; then
    /system/xbin/insmod /system/lib/modules/camise.ko
    /system/xbin/insmod /system/lib/modules/camera.ko
fi

# Camera leds sysfs has bad permissions
busybox chmod a+rw /sys/class/leds/spotlight/*
busybox chmod a+rw /sys/class/leds/torch-flash/*
busybox chown -R camera:system /sys/class/leds/torch-flash /sys/class/leds/spotlight

