#!/system/bin/sh
#

# Module location
MODULE_DIR="/system/lib/modules"
MODULE="/system/lib/modules/overclock_defy.ko"
SYMSEARCH_MODULE="/system/lib/modules/symsearch.ko"
/system/xbin/insmod $SYMSEARCH_MODULE
/system/xbin/insmod $MODULE_DIR/cpufreq_stats.ko
cpufreq_table=`grep -e omap2_clk_init_cpufreq_table /proc/kallsyms | sed -e "s/\([0-9A-Fa-f]\{8\}\).*/\1/"`
stats_update=`grep -e cpufreq_stats_freq_update /proc/kallsyms | sed -e "s/\([0-9A-Fa-f]\{8\}\).*/\1/"`
/system/xbin/insmod $MODULE omap2_clk_init_cpufreq_table_addr=0x$cpufreq_table
echo 0x$stats_update > /proc/overclock/cpufreq_stats_update_addr



