# 2nd-boot kernel module

obj-m += hbootmod.o
hbootmod-objs := hboot.o buffers.o crc32.o cache-v7.o emu_uart.o 

                                                                                                                       

