#
# Makefile for the kernel multimedia device drivers.
#

obj-y        +=	ttpci/		\
		b2c2/		\
		pluto2/		\
		dm1105/		\
		pt1/		\
		mantis/		\
		ngene/		\
		ddbridge/	\
		b2c2/		\
		saa7146/

obj-$(CPTCFG_VIDEO_IVTV) += ivtv/
obj-$(CPTCFG_VIDEO_ZORAN) += zoran/
obj-$(CPTCFG_VIDEO_CX18) += cx18/
obj-$(CPTCFG_VIDEO_CX23885) += cx23885/
obj-$(CPTCFG_VIDEO_CX25821) += cx25821/
obj-$(CPTCFG_VIDEO_CX88) += cx88/
obj-$(CPTCFG_VIDEO_BT848) += bt8xx/
obj-$(CPTCFG_VIDEO_SAA7134) += saa7134/
obj-$(CPTCFG_VIDEO_SAA7164) += saa7164/
obj-$(CPTCFG_VIDEO_MEYE) += meye/
obj-$(CPTCFG_STA2X11_VIP) += sta2x11/
