obj-y += b2c2/ saa7146/ siano/
obj-$(CPTCFG_VIDEO_CX2341X) += cx2341x.o
obj-$(CPTCFG_VIDEO_BTCX)  += btcx-risc.o
obj-$(CPTCFG_VIDEO_TVEEPROM) += tveeprom.o
obj-$(CPTCFG_CYPRESS_FIRMWARE) += cypress_firmware.o
