#
# libbluedroid
#

LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := \
	bluetooth.c

ifeq ($(BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL),true)
  LOCAL_CFLAGS := $(LOCAL_CFLAGS) -DBLUETOOTH_DOES_NOT_USE_RFKILL
endif

ifeq ($(BOARD_BLUETOOTH_USES_HCIATTACH_PROPERTY),true)
  LOCAL_CFLAGS := $(LOCAL_CFLAGS) -DBLUETOOTH_HCIATTACH_USING_PROPERTY
endif

LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/include \

LOCAL_SHARED_LIBRARIES := \
	libcutils \
	liblog

LOCAL_MODULE := libbluedroid
LOCAL_MODULE_TAGS := optional

include $(BUILD_SHARED_LIBRARY)
